force-app/main/default/objects/Booked_Trade__c/Booked_Trade__c.object-meta.xml
<CustomObject>
    <label>Booked Trade</label>
    <nameField>
        <displayFormat>TR-{0000}</displayFormat>
        <label>Booked Trades Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booked Trades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Booked_Trade__c/fields/Buy_Amount__c.field-meta.xml
<CustomField>
    <fullName>Buy_Amount__c</fullName>
    <description>Buy Amount</description>
    <label>Buy Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Booked_Trade__c/fields/Buy_Currency__c.field-meta.xml
<CustomField>
    <fullName>Buy_Currency__c</fullName>
    <description>Buy Currency</description>
    <label>Buy Currency</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booked_Trade__c/fields/Rate_Booked__c.field-meta.xml
<CustomField>
    <fullName>Rate_Booked__c</fullName>
    <description>Rate Booked</description>
    <label>Rate Booked</label>
    <precision>18</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Booked_Trade__c/fields/Sell_Amount__c.field-meta.xml
<CustomField>
    <fullName>Sell_Amount__c</fullName>
    <description>Sell Amount</description>
    <label>Sell Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Booked_Trade__c/fields/Sell_Currency__c.field-meta.xml
<CustomField>
    <fullName>Sell_Currency__c</fullName>
    <description>Sell Currency Type</description>
    <label>Sell Currency</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booked_Trade__c/fields/Trade_Id__c.field-meta.xml
<CustomField>
    <fullName>Trade_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Booked Trade Id</description>
    <externalId>true</externalId>
    <label>Trade Id</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/BookedTradesTest.cls
@IsTest
private class BookedTradesTest {

    //TEST TO CHECK OUTPUT OF DATATABLE LIST AND ASSERT NUMBER OF COLUMNS
    @IsTest
    static void testGetBookedTradeLightningDatatable() {
        List<Object> dataTable = (List<Object>) BookedTrades.getDatatableStructure();
        System.assertEquals(6, dataTable.size(), 'There should be 6 columns in datatable');
    }

    //TEST TO GET CURRENCIES USING MOCK CLASS BELOW
    @IsTest
    static void testGetCurrencies() {
        Test.setMock(HttpCalloutMock.class, new Mock());

        Test.startTest();

        List<Map<String, String>> currencies = (List<Map<String, String>>) BookedTrades.getCurrencies();
        System.assertEquals(4, currencies.size(), 'There should be 4 currencies returned');

        Test.stopTest();
    }

    //TEST TO GET RATE USING MOCK CLASS BELOW
    @IsTest
    static void testGetRates() {
        Test.setMock(HttpCalloutMock.class, new Mock());

        Test.startTest();

        Decimal rate = (Decimal) BookedTrades.getRate('AED');
        System.assertEquals(4.350666, rate, 'Rate should be 4.350666');

        Test.stopTest();
    }

    //TEST INSERTION OF BOOKED TRADE.
    @IsTest
    static void testBookedTradeInsertAndGet() {
        Test.startTest();
        Decimal bookedRate = Integer.valueOf((Math.random() * 10));
        BookedTrades.createTrade(bookedRate,
                123,
                BookedTradesTriggerHandlerTest.getRandomCurrency(),
                123 * bookedRate,
                BookedTradesTriggerHandlerTest.getRandomCurrency());


        for (Booked_Trade__c bt : BookedTrades.getBookedTrades()) {
            System.assertEquals(3, bt.Sell_Currency__c.length(), 'Sell Currency length should be 3');
            System.assertEquals(3, bt.Buy_Currency__c.length(), 'Buy Currency length should be 3');
            System.assertEquals(bt.Sell_Amount__c * bt.Rate_Booked__c, bt.Buy_Amount__c, 'Buy Amount should be Sell Amount * Rate Booked');
            System.assert(bt.Trade_Id__c.startsWith('TR'), 'Booked Trade Id should start with TR');
            System.assertEquals(9, bt.Trade_Id__c.length(), 'Booked Trade Id length should be 9');
        }

        Test.stopTest();
    }

    //MOCK CLASS TO TEST API CALLOUTS.
    private class Mock implements HttpCalloutMock {

        public HttpResponse respond(HttpRequest req) {

            HttpResponse res = new HttpResponse();

            if (req.getEndpoint() == Settings.FIXER_SYMBOLS_API) {
                res.setBody('{"success":true,"symbols":{"EUR":"Euro","INR":"Indian Rupee","GBP":"British Pound Sterling","USD":"United States Dollar"}}');
                res.setStatusCode(200);
            } else if (req.getEndpoint() == Settings.FIXER_LATEST_API) {
                res.setBody('{"success":true,"timestamp":1600461544,"base":"EUR","date":"2020-09-18","rates":{"AED":4.350666,"AFN":91.002923,"ALL":123.963391}}');
                res.setStatusCode(200);
            }

            return res;
        }

    }

    //SETUP INITIAL DATA.
    @TestSetup
    static void setupData() {
        List<Booked_Trade__c> bookedTrades = new List<Booked_Trade__c>();
        for (Integer counter = 1; counter < 200; counter++) {
            bookedTrades.add(BookedTradesTriggerHandlerTest.createBookedTrade(counter));
        }
        insert bookedTrades;
    }
}