force-app/main/default/objects/Booked_Trade__c/Booked_Trade__c.object-meta.xml
<CustomObject>
    <label>Booked Trade</label>
    <nameField>
        <displayFormat>TR-{0000}</displayFormat>
        <label>Booked Trades Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booked Trades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Booked_Trade__c/fields/Buy_Amount__c.field-meta.xml
<CustomField>
    <fullName>Buy_Amount__c</fullName>
    <description>Buy Amount</description>
    <label>Buy Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Booked_Trade__c/fields/Buy_Currency__c.field-meta.xml
<CustomField>
    <fullName>Buy_Currency__c</fullName>
    <description>Buy Currency</description>
    <label>Buy Currency</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booked_Trade__c/fields/Rate_Booked__c.field-meta.xml
<CustomField>
    <fullName>Rate_Booked__c</fullName>
    <description>Rate Booked</description>
    <label>Rate Booked</label>
    <precision>18</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Booked_Trade__c/fields/Sell_Amount__c.field-meta.xml
<CustomField>
    <fullName>Sell_Amount__c</fullName>
    <description>Sell Amount</description>
    <label>Sell Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Booked_Trade__c/fields/Sell_Currency__c.field-meta.xml
<CustomField>
    <fullName>Sell_Currency__c</fullName>
    <description>Sell Currency Type</description>
    <label>Sell Currency</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booked_Trade__c/fields/Trade_Id__c.field-meta.xml
<CustomField>
    <fullName>Trade_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Booked Trade Id</description>
    <externalId>true</externalId>
    <label>Trade Id</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/BookedTradesTriggerHandler.cls
//SINGLETON CLASS TO HANDLE TRIGGER LOGIC FOR Booked_Trade__c
public with sharing class BookedTradesTriggerHandler {

    private static BookedTradesTriggerHandler instance;
    private static List<Group> queue;
    @TestVisible private static List<GroupMember> groupMembers;
    @TestVisible private static List<ConnectApi.BatchInput> batchInputs;

    public static BookedTradesTriggerHandler getInstance() {
        return instance == null ? new BookedTradesTriggerHandler() : instance;
    }

    private BookedTradesTriggerHandler() {
        queue = [SELECT Id FROM Group WHERE Type = 'Queue' AND Name = :Settings.QUEUE_TRADE_REVIEWERS];
        groupMembers = [SELECT UserOrGroupId FROM GroupMember WHERE GroupId IN :queue];
        batchInputs = new List<ConnectApi.BatchInput>();
    }

    //SET THE TRADE ID beforeInsert
    public void setTradesId(List<Booked_Trade__c> newList) {
        for (Booked_Trade__c bt : newList) {
            bt.Trade_Id__c = Settings.BOOKED_TRADE_ID_PREFIX + Utility.generateRandomString(7);
        }
    }

    //POST TO CHATTER AFTER THE TRADE IS CREATED
    public void postChatter(List<Booked_Trade__c> newList) {
        for (Booked_Trade__c bt : newList) {
            String content = 'A new trade has been created with the following data:';
            content += '\r\nSell Currency: ' + bt.Sell_Currency__c;
            content += '\r\nSell Amount: ' + bt.Sell_Amount__c;
            content += '\r\nBuy Currency: ' + bt.Buy_Currency__c;
            content += '\r\nBuy Amount: ' + bt.Buy_Amount__c;
            content += '\r\nRate: ' + bt.Rate_Booked__c;
            content += '\r\nBooked Date: ' + bt.CreatedDate.format('dd MMMM yyyy, HH:mm:ss');
			
            for (GroupMember member : groupMembers) {
                ConnectApi.BatchInput batchInput = new ConnectApi.BatchInput(Utility.chatterTextPost(member.UserOrGroupId, content));
                batchInputs.add(batchInput);
            }
        }

        //BYPASSING THE TEST HERE AS WE NEED TO SET SEEALLDATA = TRUE, BASED ON MY EXPERIENCE, I'M A BIT HESITANT TO DO THIS.
        if (!Test.isRunningTest()) {
            ConnectApi.ChatterFeeds.postFeedElementBatch(Network.getNetworkId(), batchInputs);
        }
    }
}