force-app/main/default/objects/Booked_Trade__c/Booked_Trade__c.object-meta.xml
<CustomObject>
    <label>Booked Trade</label>
    <nameField>
        <displayFormat>TR-{0000}</displayFormat>
        <label>Booked Trades Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booked Trades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Booked_Trade__c/fields/Buy_Amount__c.field-meta.xml
<CustomField>
    <fullName>Buy_Amount__c</fullName>
    <description>Buy Amount</description>
    <label>Buy Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Booked_Trade__c/fields/Buy_Currency__c.field-meta.xml
<CustomField>
    <fullName>Buy_Currency__c</fullName>
    <description>Buy Currency</description>
    <label>Buy Currency</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booked_Trade__c/fields/Rate_Booked__c.field-meta.xml
<CustomField>
    <fullName>Rate_Booked__c</fullName>
    <description>Rate Booked</description>
    <label>Rate Booked</label>
    <precision>18</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Booked_Trade__c/fields/Sell_Amount__c.field-meta.xml
<CustomField>
    <fullName>Sell_Amount__c</fullName>
    <description>Sell Amount</description>
    <label>Sell Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Booked_Trade__c/fields/Sell_Currency__c.field-meta.xml
<CustomField>
    <fullName>Sell_Currency__c</fullName>
    <description>Sell Currency Type</description>
    <label>Sell Currency</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booked_Trade__c/fields/Trade_Id__c.field-meta.xml
<CustomField>
    <fullName>Trade_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Booked Trade Id</description>
    <externalId>true</externalId>
    <label>Trade Id</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/BookedTrades.cls
//CLASS TO SUPPORT UI FUNCTIONS FOR BookedTrades
public with sharing class BookedTrades {

    public static final String DATATABLE_BOOKED_TRADES = 'Booked_Trades';

    //GET DATATABLE FROM Utility CLASS FOR Booked Trades
    @AuraEnabled
    public static Object getDatatableStructure() {
        return Utility.getLightningDatatable(DATATABLE_BOOKED_TRADES);
    }

    //GET CURRENCIES FROM Fixer API
    @AuraEnabled
    public static Object getCurrencies() {
        try {
            Map<String, Object> currencyData = (Map<String, Object>) JSON.deserializeUntyped(Utility.getFixerAPIData(Settings.FIXER_SYMBOLS_API));
            Map<String, Object> currencies = (Map<String, Object>) currencyData.get('symbols');

            List<Map<String, String>> currencyPicklist = new List<Map<String, String>>();
            for (String option : currencies.keySet()) {
                currencyPicklist.add(new Map<String, String>{
                        'option' => option, 'label' => option + ' - ' + (String) currencies.get(option)
                });
            }

            return currencyPicklist;
        } catch (Exception ex) {
            return new Map<String, String>{
                    'failed' => 'Unable to get currencies, Please ask support from Admins'
            };
        }
    }

    //GET Rate FOR CURRENCY PASSED FROM LIGHTNING COMPONENT
    @AuraEnabled
    public static Object getRate(String currencyToGet) {
        try {
            Map<String, Object> ratesData = (Map<String, Object>) JSON.deserializeUntyped(Utility.getFixerAPIData(Settings.FIXER_LATEST_API));
            Map<String, Object> currencies = (Map<String, Object>) ratesData.get('rates');

            return currencies.get(currencyToGet);
        } catch (Exception ex) {
            return new Map<String, String>{
                    'failed' => 'Unable to get Rate for ' + currencyToGet + ', Please ask support from Admins'
            };
        }
    }

    //GET ALL BOOKED TRADES TO SHOW ON UI
    @AuraEnabled
    public static List<Booked_Trade__c> getBookedTrades() {
        return [
                SELECT Id, Trade_Id__c, Sell_Amount__c, Sell_Currency__c, Buy_Amount__c, Buy_Currency__c, Rate_Booked__c, CreatedDate
                FROM Booked_Trade__c
                ORDER BY CreatedDate DESC
        ];
    }

    //CREATE A NEW BOOKED TRADE RECORD.
    @AuraEnabled
    public static Object createTrade(Decimal rateBooked, Decimal sellAmount, String sellCurrency, Decimal buyAmount, String buyCurrency) {
        Database.SaveResult saveResults;
        try {
            Booked_Trade__c bt = new Booked_Trade__c();
            bt.Rate_Booked__c = rateBooked;
            bt.Sell_Amount__c = sellAmount;
            bt.Sell_Currency__c = sellCurrency;
            bt.Buy_Currency__c = buyCurrency;
            bt.Buy_Amount__c = buyAmount;

            saveResults = Database.insert(bt);
            return bt;
        } catch (Exception ex) {
            return new Map<String, String>{
                    'failed' => saveResults.getErrors()[0].getMessage()
            };
        }
    }
}